# Generated by Django 4.2.6 on 2023-10-26 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(verbose_name='Income')),
                ('savings', models.IntegerField(blank=True, default=0, verbose_name='Savings')),
                ('remaining', models.IntegerField(default=0, verbose_name='Remaining Income')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expenditures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.IntegerField(blank=True, default=0, verbose_name='Rent')),
                ('leisure', models.IntegerField(blank=True, default=0, verbose_name='Leisure')),
                ('grocery', models.IntegerField(blank=True, default=0, verbose_name='Grocery')),
                ('others', models.IntegerField(blank=True, default=0, verbose_name='Others')),
                ('month', models.IntegerField(blank=True, default=0, verbose_name='Month')),
                ('year', models.IntegerField(blank=True, default=0, verbose_name='Year')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
