# Generated by Django 4.2.6 on 2023-10-07 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Income", models.IntegerField(verbose_name="Income")),
                (
                    "Savings",
                    models.IntegerField(blank=True, default=0, verbose_name="Savings"),
                ),
                (
                    "Remaining",
                    models.IntegerField(default=0, verbose_name="Remaining Income"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("LoginName", models.TextField(verbose_name="Name")),
                ("LoginPassword", models.TextField(verbose_name="Password")),
                (
                    "UserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bugetPlanner.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expenditures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rent",
                    models.IntegerField(blank=True, default=0, verbose_name="Rent"),
                ),
                (
                    "leisure",
                    models.IntegerField(blank=True, default=0, verbose_name="Leisure"),
                ),
                (
                    "grocery",
                    models.IntegerField(blank=True, default=0, verbose_name="Grocery"),
                ),
                (
                    "others",
                    models.IntegerField(blank=True, default=0, verbose_name="Others"),
                ),
                (
                    "month",
                    models.IntegerField(blank=True, default=0, verbose_name="Month"),
                ),
                (
                    "year",
                    models.IntegerField(blank=True, default=0, verbose_name="Year"),
                ),
                (
                    "UserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bugetPlanner.users",
                    ),
                ),
            ],
        ),
    ]
