# Generated by Django 4.2.6 on 2023-10-26 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bugetPlanner", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="expenditures", name="month",),
        migrations.RemoveField(model_name="expenditures", name="year",),
        migrations.AddField(
            model_name="expenditures",
            name="date_and_time",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
